name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  ime:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  Vreme: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'bin/index.js'