name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  owner:  # Source repo owner
    description: 'Source repository owner'
    required: true
    default: ''
  repo:  # id of input
    description: 'Source repository name'
    required: true
    default: ''
  ref:  # id of input
    description: 'Branch name or tag'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'bin/index.js'