on: [push]

name: Test

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: ljubon/poc-action@v1.2
        with:
          owner: 'marijana'
          repo: 'kida'
          ref: 'v1000'
      # Use the output from the `hello` step
      - name: Get the output Vreme
        run: echo "The Vreme was ${{ steps.hello.outputs.Vreme }}"